version: '3.8'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: morphosium
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
